//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmidID.Web.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmidID.Web.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection name not specified.
        /// </summary>
        internal static string Connection_name_not_specified {
            get {
                return ResourceManager.GetString("Connection_name_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string not found.
        /// </summary>
        internal static string Connection_string_not_found {
            get {
                return ResourceManager.GetString("Connection_string_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetNumberOfUsersOnline not supported..
        /// </summary>
        internal static string GetNumberOfUsersOnline_not_supported {
            get {
                return ResourceManager.GetString("GetNumberOfUsersOnline_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hash algorithm type &quot;{0}&quot;.
        /// </summary>
        internal static string Invalid_hash_algorithm_type {
            get {
                return ResourceManager.GetString("Invalid_hash_algorithm_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordRetrieval not supported.
        /// </summary>
        internal static string Membership_PasswordRetrieval_not_supported {
            get {
                return ResourceManager.GetString("Membership_PasswordRetrieval_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership provider not found.
        /// </summary>
        internal static string Membership_provider_not_found {
            get {
                return ResourceManager.GetString("Membership_provider_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min required nonalphanumeric characters can not be more than Min required password length.
        /// </summary>
        internal static string MinRequiredNonalphanumericCharacters_can_not_be_more_than_MinRequiredPasswordLength {
            get {
                return ResourceManager.GetString("MinRequiredNonalphanumericCharacters_can_not_be_more_than_MinRequiredPasswordLeng" +
                        "th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not configured to support password resets.
        /// </summary>
        internal static string Not_configured_to_support_password_resets {
            get {
                return ResourceManager.GetString("Not_configured_to_support_password_resets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider application name too long.
        /// </summary>
        internal static string Provider_application_name_too_long {
            get {
                return ResourceManager.GetString("Provider_application_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider bad password format.
        /// </summary>
        internal static string Provider_bad_password_format {
            get {
                return ResourceManager.GetString("Provider_bad_password_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider can not decode hashed password.
        /// </summary>
        internal static string Provider_can_not_decode_hashed_password {
            get {
                return ResourceManager.GetString("Provider_can_not_decode_hashed_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider can not retrieve hashed password.
        /// </summary>
        internal static string Provider_can_not_retrieve_hashed_password {
            get {
                return ResourceManager.GetString("Provider_can_not_retrieve_hashed_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionAndAnswer not supported.
        /// </summary>
        internal static string QuestionAndAnswer_not_supported {
            get {
                return ResourceManager.GetString("QuestionAndAnswer_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection can not cast type of {0} to {1}.
        /// </summary>
        internal static string Reflection_can_not_cast_object {
            get {
                return ResourceManager.GetString("Reflection_can_not_cast_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is required.
        /// </summary>
        internal static string Reflection_property_is_required {
            get {
                return ResourceManager.GetString("Reflection_property_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID type is not match.
        /// </summary>
        internal static string Reflection_UserID_type_is_not_match {
            get {
                return ResourceManager.GetString("Reflection_UserID_type_is_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be boolean, {0}.
        /// </summary>
        internal static string Value_must_be_boolean {
            get {
                return ResourceManager.GetString("Value_must_be_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be non negative integer, {0}.
        /// </summary>
        internal static string Value_must_be_non_negative_integer {
            get {
                return ResourceManager.GetString("Value_must_be_non_negative_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive integer, {0}.
        /// </summary>
        internal static string Value_must_be_positive_integer {
            get {
                return ResourceManager.GetString("Value_must_be_positive_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value too big, {0}, max: {1}.
        /// </summary>
        internal static string Value_too_big {
            get {
                return ResourceManager.GetString("Value_too_big", resourceCulture);
            }
        }
    }
}
